# _*_ mode:org _*_
#+TITLE: data-structures
#+STARTUP: indent
#+OPTIONS: toc:nil

[[file:math.org::*further%20benefits][The relevance of this topic can be seen here]] .  I'd say more but one
of the purported benefits of this new system is that there is less
duplication which I think is a fine goal.


* The fundamental distinctions

- fundamental structures
- mathematical structures


In short fudamental structures are concepts which map directly into
the architecture of the digital computer and defined in terms of its
primitive operations. Essentially this amounts to linear lists, trees
and sets.  Additionally fundamental structures are aptly name since
they are the building blocks upon which all programs are built and by
their natures can be subtyped in to special purpose data-structures
with varying space and time complexity.

Mathematical structures are structures which map directly to the
machinery of modern mathematics, and only incidentally are
implementable on a digital computer.




















# Local Variables:
# eval: (wiki-mode)
# End:
