# -*- mode:org -*-
#+TITLE: sets
#+STARTUP: indent
#+OPTIONS: toc:nil

so another important mathematical concept, like the sequence of the
matrix.  Its hard to understand how fundamental a set is, its kind of
a like a meta structures.  How is a set different than a sequence?
Well a sequence can be thought of in terms of a set with repeating
elements.

Basically I don't know if sets are as fundamental to computer science
as they are to mathematics, but they do offer a useful abstraction, a
collection of unique items.  This is the basis of the associative
array data structure, we have a single key and a single value.  Sounds
like a function eh?  Well functions are mappings from one set to
another so that is an appropriate relation.  Also relations are a
thing.  I hate mathematical terminology.

However when we're talking about computer science, a set is primarily
a way to compute:

1. a unique collection of values
2. an implementation of a mathematical function, a mapping of keys to
   values

yeah, idk that's still kind of vague.


./sets/insert
./sets/extract-max
./sets/delete
./sets/random-sample
./sets/make-set
./sets/search
./sets/find-set
./sets/print-set
./sets/increase-key

